ClassMate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profile/', include('profiles.urls')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [

    # profile
    path('', views.profile, name='profile'),
    path('<int:user_id>/', views.viewprofile, name='viewprofile'),

    # New profile
    path('create_user/', views.create_user, name='create_user'),
    path('create/', views.create, name='create'),

    # Search
    path('search/', views.search, name='search'),
]

profiles/models.py
from django.db import models
from accounts.models import MyUser, MyUserManager

class TutorManager(models.Manager):
    def create_tutor(self, user, name):
        profile = self.model(user=user, name=name)
        profile.save(using=self._db)
        return profile

class TeacherManager(models.Manager):
    def create_teacher(self, user, name):
        profile = self.model(user=user, name=name)
        profile.save(using=self._db)
        return profile

class StudentManager(models.Manager):
    def create_student(self, user, name):
        profile = self.model(user=user, name=name)
        profile.save(using=self._db)
        return profile

class ParentManager(models.Manager):
    def create_parent(self, user, name):
        profile = self.model(user=user, name=name)
        profile.save(using=self._db)
        return profile



class TutorProfile(models.Model):
    user = models.OneToOneField(
        MyUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    school = models.CharField(
        verbose_name='school',
        max_length=100,
        default=''
    )

    name = models.CharField(
        verbose_name='name',
        max_length=100,
        default='',
    )

    clients = models.IntegerField(
        verbose_name='clients',
        default=0,
    )

    subjects = models.TextField(
        verbose_name='subjects',
        max_length=400,
        default='',
    )

    major = models.CharField(
        verbose_name='major',
        max_length=50,
        default='',
    )

    accommodations = models.IntegerField(
        verbose_name='accommodations',
        default=0,
    )

    def __str__(self):
        return self.name

    objects = TutorManager()

class TeacherProfile(models.Model):
    user = models.OneToOneField(
        MyUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    school = models.CharField(
        verbose_name='school',
        max_length=255,
        default='',
    )

    name = models.CharField(
        verbose_name='name',
        max_length=100,
        default='',
    )

    gradelevel = models.CharField(
        verbose_name='gradelevel',
        max_length=20,
        default='',
    )

    def __str__(self):
        return self.name

    objects = TeacherManager()

class StudentProfile(models.Model):
    user = models.OneToOneField(
        MyUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    school = models.CharField(
        verbose_name='school',
        max_length=255,
        default='',
    )

    name = models.CharField(
        verbose_name='name',
        max_length=100,
        default='',
    )

    gradelevel = models.CharField(
        verbose_name='gradelevel',
        max_length=20,
        default='',
    )


    def __str__(self):
        return self.name

    objects = StudentManager()

class ParentProfile(models.Model):
    user = models.OneToOneField(
        MyUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    school = models.CharField(
        verbose_name='school',
        max_length=255,
        default='',
    )

    name = models.CharField(
        verbose_name='name',
        max_length=100,
        default='',
    )

    gradelevel = models.CharField(
        verbose_name='gradelevel',
        max_length=20,
        default='',
    )

    def __str__(self):
        return self.name

    objects = ParentManager()

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from accounts.models import MyUser, MyUserManager
from django.contrib.auth import get_user_model
from .models import TutorProfile, StudentProfile, TeacherProfile, ParentProfile
from . import data
from django.contrib.auth.decorators import login_required

@login_required(login_url='accounts:loginuser')
def profile(request):
    if request.method == 'GET':
        return render(request, 'profiles/profile.html', {'person':request.user})
    else:
        return render(request, 'profiles/profile.html', {'person':request.POST['person']})

@login_required(login_url='accounts:loginuser')
def search(request):

    if request.user.type == 'tutor':
        return redirect('main:home')
    else:
        if request.method == 'GET':
            return render(request, 'profiles/search.html', {'subjects':data.subjects})
        else:
            tutor_list = []
            for tutor in TutorProfile.objects.all():
                tutor_list.append(tutor.user_id)
            client = 0
            if request.user.type == 'teacher':
                client = 1
            else:
                client = 2

            accommodations = request.POST.getlist('accommodations')
            acc = 0
            if 'ESL' in accommodations:
                acc += 1
            if 'Special Needs' in accommodations:
                acc += 2

            chosen_subjects = request.POST.getlist('subjects')

            if acc > 0:
                tutor_list = [tutor for tutor in tutor_list if
                (TutorProfile.objects.get(user_id=tutor).clients == 3 or TutorProfile.objects.get(user_id=tutor).clients == client)
                and (TutorProfile.objects.get(user_id=tutor).accommodations == acc or TutorProfile.objects.get(user_id=tutor).accommodations == 3)
                and data.common(TutorProfile.objects.get(user_id=tutor).subjects.split(', '), chosen_subjects)]


            else:
                tutor_list = [tutor for tutor in tutor_list if
                (TutorProfile.objects.get(user_id=tutor).clients == 3 or TutorProfile.objects.get(user_id=tutor).clients == client)
                and data.common(TutorProfile.objects.get(user_id=tutor).subjects.split(', '), chosen_subjects)]

            return render(request, 'profiles/results.html', {'tutors':TutorProfile.objects.all(), 'ids':tutor_list})

@login_required(login_url='accounts:loginuser')
def viewprofile(request, user_id):
    person = get_object_or_404(TutorProfile, user_id=user_id)
    return render(request, 'profiles/profile.html', {'person':person.user})

def create_user(request):

    if request.user.type == 'tutor':

        profile = TutorProfile.objects.create_tutor(request.user, request.user.name)
        school = request.user.email.split('@')[1]
        profile.school = data.tutor_schools[school]
        profile.save()

        return redirect('profiles:create')

    if request.user.type == 'teacher':

        profile = TeacherProfile.objects.create_teacher(request.user, request.user.name)
        profile.save()

        return redirect('profiles:create')

    if request.user.type == 'student':

        profile = StudentProfile.objects.create_student(request.user, request.user.name)
        profile.save()

        return redirect('profiles:create')

    if request.user.type == 'parent':

        profile = ParentProfile.objects.create_parent(request.user, request.user.name)
        profile.save()

        return redirect('profiles:create')

def create(request):
    name = request.user.name.split()[0]


    if request.user.type == 'tutor':
        if request.method == 'GET':
            return render(request, 'profiles/create.html', {'name':name, 'subjects':data.subjects})
        else:
            user = TutorProfile.objects.get(user_id=request.user.id)
            chosen_subjects = request.POST.getlist('subjects')
            user.subjects = ', '.join(chosen_subjects)
            user.major = request.POST['major']
            if request.POST['teacher'] == 'yes':
                user.clients += 1
            if request.POST['student'] == 'yes':
                user.clients += 2
            if 'ESL' in request.POST:
                user.accommodations += 1
            if 'Special Needs' in request.POST:
                user.accommodations += 2
            user.save()
            return redirect('main:home')

    if request.user.type == 'teacher':
        if request.method == 'GET':
            return render(request, 'profiles/create.html', {'name':name, 'schools':data.teacher_schools})
        else:
            user = TeacherProfile.objects.get(user_id=request.user.id)
            user.school = request.POST['school']
            user.gradelevel = request.POST['gradelevel']
            user.save()
            return redirect('main:home')

    if request.user.type == 'student':
        if request.method == 'GET':
            return render(request, 'profiles/create.html', {'name':name, 'schools':data.schools})
        else:
            user = StudentProfile.objects.get(user_id=request.user.id)
            user.school = request.POST['school']
            user.gradelevel = request.POST['gradelevel']
            user.save()
            return redirect('main:home')

    if request.user.type == 'parent':
        if request.method == 'GET':
            return render(request, 'profiles/create.html', {'name':name, 'schools':data.schools})
        else:
            user = ParentProfile.objects.get(user_id=request.user.id)
            user.school = request.POST['school']
            user.save()
            return redirect('main:home')

profiles/templates/profiles/create.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Hi, {{ name }}. Let's talk about you.</h1>

<form method="POST">
  {% csrf_token %}
  {% if user.type != 'tutor' %}
  <h5>What school do you {% if user.type == 'student' %}go to?{% endif %}{% if user.type == 'teacher' %}work at?{% endif %}{% if user.type == 'parent' %}have a student at?{% endif %}</h5>
  <select name="school">
    {% for school in schools %}
    <option value="{{ school }}">{{ school }}</option>
    {% endfor %}
  </select>
  {% if user.type != 'parent' %}
  <h5>What grade level do you need tutors for?</h5>
  <select name="gradelevel">
    <option value="elementary">Elementary</option>
    <option value="middle">Middle School</option>
    <option value="high">High School</option>
  </select>
  {% endif %}
  {% endif %}

  <br>
  <br>

  {% if user.type == 'tutor' %}
  <h5>What subjects would you like to tutor? To select multiple, use ctrl-click on windows or cmd-click on mac.</h5>
  <select name="subjects" multiple>
    {% for subject in subjects %}
    <option value="{{ subject }}">{{ subject }}</option>
    {% endfor %}
  </select>

  <h5>What is your major?</h5>
  <p>
    <input type="text" name="major">
  </p>

  <h5>Would you like teachers to be able to find you via searches?</h5>
  <input type="radio" id="yes" name="teacher" value="yes">
  <label for="yes">Yes</label><br>
  <input type="radio" id="no" name="teacher" value="no">
  <label for="no">No</label><br>

  <h5>Would you like students and parents to be able to find you via searches?</h5>
  <input type="radio" id="yes" name="student" value="yes">
  <label for="yes">Yes</label><br>
  <input type="radio" id="no" name="student" value="no">
  <label for="no">No</label><br>

  <h5>Are you able to make any of the following special accommodations?</h5>
  <input type="checkbox" id="ESL" name="ESL" value="ESL">
  <label for="ESL">ESL</label><br>
  <input type="checkbox" id="Special Needs" name="Special Needs" value="Special Needs">
  <label for="Special Needs">Special Needs</label><br>

  {% endif %}

  <button class="btn btn-outline-dark" type="submit">Done</button>

</form>

{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'main/base.html' %}

{% block content %}

{{ person.name }}
<br>
{{ person.email }}
<br>
{% if person.type == 'tutor' %}
{{ person.tutorprofile.school }}
<br>
{{ person.tutorprofile.subjects }}
{% endif %}
{% if person.type == 'teacher' %}
{{ person.teacherprofile.school }}
<br>
{{ person.teacherprofile.subjects }}
{% endif %}
{% if person.type == 'student' %}
{{ person.studentprofile.school }}
{% endif %}
{% if person.type == 'parent' %}
{{ person.parentprofile.school }}
{% endif %}
{% endblock %}

profiles/templates/profiles/results.html
{% extends 'main/base.html' %}

{% block content %}

<div>
  <table class="table table-bordered">

      {% csrf_token %}
      {% for tutor in tutors %}
      {% if tutor.user_id in ids %}
      <tr>
        <td>{{ tutor.name }}</td>
        <td>{{ tutor.school }}</td>
        <td>{{ tutor.major }}</td>
        <td>
          <a href="{% url 'profiles:viewprofile' tutor.user_id %}">Profile</a>
        </td>
      </tr>
    {% endif %}
    {% endfor %}

  </table>
</div>
{% endblock %}

profiles/templates/profiles/search.html
{% extends 'main/base.html' %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <h1>Search</h1>
  <h3>Use this tool to find a tutor that fits your needs!</h3>
  <br>
  <h5>What subjects would you like to find tutors for? To select multiple, use ctrl-click on windows or cmd-click on mac.</h5>
  <select name="subjects" multiple required>
    {% for subject in subjects %}
    <option value="{{ subject }}">{{ subject }}</option>
    {% endfor %}
  </select>
  <br><br>
  <h5>Do you need any of the following accommodations to be met?</h5>
  <input type="checkbox" id="ESL" name="accommodations" value="ESL">
  <label for="ESL">ESL</label><br>
  <input type="checkbox" id="Special Needs" name="accommodations" value="Special Needs">
  <label for="Special Needs">Special Needs</label><br>
  <br>
  <button class="btn btn-outline-dark" type="submit">Search</button>
</form>
{% endblock %}