ClassMate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profile/', include('profiles.urls')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    # Account creation
    path('signup/', views.signupuser, name='signupuser'),
    path('signup/tutor/', views.tutor, name='tutor'),
    path('signup/teacher/', views.teacher, name='teacher'),
    path('signup/student/', views.student, name='student'),
    path('signup/parent/', views.parent, name='parent'),

    # Authentication
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, name, type, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
            name=name,
            type=type,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(
        verbose_name='name',
        max_length=255,
        default="no name",
    )
    type = models.CharField(
        verbose_name='type',
        max_length=50,
        default='none',
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, views, logout
from django.contrib.auth.forms import AuthenticationForm
from .models import MyUser
from django.db import IntegrityError
from profiles.models import TutorProfile, StudentProfile

def signupuser(request):
    if request.method == 'GET':
        return render(request, 'accounts/signupuser.html')
    else:
        pass

def tutor(request):

    schools = {
        '@oakland.edu':'Oakland University',
        '@umich.edu':'University of Michigan Ann Arbor',
    }

    if request.method == 'GET':
        return render(request, 'accounts/signuptutor.html', {'schools':schools.keys()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            email = request.POST['username'] + request.POST['school']
            try:
                user = MyUser.objects.create_user(
                    email,
                    request.POST['date_of_birth'],
                    request.POST['name'],
                    'tutor',
                    password=request.POST['password1']
                )
                user.save()
                login(request, user)
                return redirect('profiles:create_user')
            except IntegrityError:
                return render(request, 'accounts/signuptutor.html', {'error':'Email is already in use', 'schools':schools.keys()})
        else:
            return render(request, 'accounts/signuptutor.html', {'error':'Passwords did not match', 'schools':schools.keys()})

def teacher(request):

    schools = [
        '@uticak12.org',
    ]

    if request.method == 'GET':
        return render(request, 'accounts/signuptutor.html', {'schools':schools})
    else:
        if request.POST['password1'] == request.POST['password2']:
            email = request.POST['username'] + request.POST['school']
            try:
                user = MyUser.objects.create_user(
                    email,
                    request.POST['date_of_birth'],
                    request.POST['name'],
                    'teacher',
                    password=request.POST['password1']
                )
                user.save()
                login(request, user)
                return redirect('profiles:create_user')
            except IntegrityError:
                return render(request, 'accounts/signuptutor.html', {'error':'Email is already in use', 'schools':schools})
        else:
            return render(request, 'accounts/signuptutor.html', {'error':'Passwords did not match', 'schools':schools})

def student(request):
        if request.method == 'GET':
            return render(request, 'accounts/signupparent.html')
        else:
            if request.POST['password1'] == request.POST['password2']:
                try:
                    user = MyUser.objects.create_user(
                        request.POST['username'],
                        request.POST['date_of_birth'],
                        request.POST['name'],
                        'student',
                        password=request.POST['password1']
                    )
                    user.save()
                    login(request, user)
                    return redirect('profiles:create_user')
                except IntegrityError:
                    return render(request, 'accounts/signupparent.html', {'error':'Email is already in use'})
            else:
                return render(request, 'accounts/signupparent.html', {'error':'Passwords did not match'})

def parent(request):
    if request.method == 'GET':
        return render(request, 'accounts/signupparent.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = MyUser.objects.create_user(
                    request.POST['username'],
                    request.POST['date_of_birth'],
                    request.POST['name'],
                    'parent',
                    password=request.POST['password1']
                )
                user.save()
                login(request, user)
                return redirect('profiles:create_user')
            except IntegrityError:
                return render(request, 'accounts/signupparent.html', {'error':'Email is already in use'})
        else:
            return render(request, 'accounts/signupparent.html', {'error':'Passwords did not match'})

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'accounts/loginuser.html', {'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'accounts/loginuser.html', {'form':AuthenticationForm(), 'error':'Username and password do not match'})
        else:
            login(request, user)
            return redirect('main:home')

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('main:home')

accounts/templates/accounts/loginuser.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Login</h1>

<h2>{{ error }}</h2>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>

</form>

{% endblock %}

accounts/templates/accounts/signupparent.html
{% extends 'main/base.html' %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <p>
    <label for="name">Name:</label>
    <input type="text" name="name" autocomplete="name" required id="name">
  </p>
  <p>
    <label for="id_username">Email:</label>
    <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
  </p>
  <p>
    <label for="date_of_birth">Date of birth:</label>
    <input type="date" name="date_of_birth" autocomplete="date_of_birth" required id="date_of_birth">
  </p>
  <p>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
  </p>
  <p>
    <label for="id_password2">Confirm Password:</label>
    <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
  </p>
  <p>{{ error }}</p>
  <button class="btn btn-outline-dark" type="submit">Sign Up</button>
</form>
{% endblock %}

accounts/templates/accounts/signuptutor.html
{% extends 'main/base.html' %}

{% block content %}


<form method="POST">
  {% csrf_token %}
  <p>
    <label for="name">Name:</label>
    <input type="text" name="name" autocomplete="name" required id="name">
  </p>
  <p>
    <label for="id_username">Email:</label>
    <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
    <select name="school">
      {% for school in schools %}
      <option value="{{ school }}">{{ school }}</option>
      {% endfor %}
    </select>
  </p>
  <p>
    <label for="date_of_birth">Date of birth:</label>
    <input type="date" name="date_of_birth" autocomplete="date_of_birth" required id="date_of_birth">
  </p>
  <p>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
  </p>
  <p>
    <label for="id_password2">Confirm Password:</label>
    <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
  </p>
  <p style="color: red">{{ error }}</p>
  <button class="btn btn-outline-dark" type="submit">Sign Up</button>
</form>
{% endblock %}

accounts/templates/accounts/signupuser.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Welcome to ClassMate!</h1>

<h4>I am a:</h4>

<a href="{% url 'accounts:tutor' %}">
  <button class="btn btn-outline-dark">Tutor</button>
</a>
<a href="{% url 'accounts:teacher' %}">
  <button class="btn btn-outline-dark">Teacher</button>
</a>
<a href="{% url 'accounts:student' %}">
  <button class="btn btn-outline-dark">Student</button>
</a>
<a href="{% url 'accounts:parent' %}">
  <button class="btn btn-outline-dark">Parent</button>
</a>

{% endblock %}