ClassMate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profile/', include('profiles.urls')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    # Account creation
    path('signup/', views.signupuser, name='signupuser'),
    path('signup/tutor/', views.tutor, name='tutor'),
    path('signup/teacher/', views.teacher, name='teacher'),
    path('signup/student/', views.student, name='student'),
    path('signup/parent/', views.parent, name='parent'),

    # Authentication
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [

    # profile
    path('', views.profile, name='profile'),
    path('<int:user_id>/', views.viewprofile, name='viewprofile'),

    # New profile
    path('create_user/', views.create_user, name='create_user'),
    path('create/', views.create, name='create'),

    # Search
    path('search/', views.search, name='search'),
]

main/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'main/home.html')

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>ClassMate</title>
  </head>
  <body>
    <div class="content-center">

      <nav class="navbar navbar-light navbar-expand" style="background-color: #29335C;">
      <!-- Navbar content -->
        <div class="container">
          <a class="navbar-brand" href="{% url 'main:home' %}" style="color: white">ClassMate</a>


          {% if user.is_authenticated %}
          <ul class="navbar-nav mb-auto">
            <li class="nav-item">
              <a href="{% url 'profiles:profile' %}" class="nav-link" style="color: white">Hello, {{ user.name }}</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logoutuser' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-secondary" type="submit">Logout</button>
              </form>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav mb-auto">
            <li class="nav-item">
              <a href="{% url 'accounts:loginuser' %}" class="nav-link" style="color: white">Login</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:signupuser' %}" class="nav-link" style="color: white">Sign Up</a>
            </li>
          </ul>
          {% endif %}
        </nav>
      </div>
    </div>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
{% if not user.is_authenticated %}
<h1>Welcome to ClassMate</h1>
<br>
<h5>If it's your first time here, read on for some helpful tips to use this site.</h5>
<p class="col-9">
  The inspiration for the ClassMate tool is to lend a helping hand to K12 teachers, students, and parents
  in tackling COVID-19 learning. Our youth deserve the best education we can give them, pandemic or not.
</p>
<p class="col-9">
  Teachers, students, and parents acrossed the nation have voiced their concerns of being underequipped,
  underprepared, and understaffed for efficient online learning. Parents who are forced to school their
  children at home often cannot even afford the time!
</p>
<p class="col-9">
  Through ClassMate, university students are invited to volunteer their time to tutor and supplement the
  education of K12 students via online interation both with the students themselves and their teachers.

</p>
{% endif %}
{% endblock %}